[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["python"]

[deploy]
startCommand = "python start.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"